env: local

data:
  data_path_local: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/data/
  models_path_local: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/
  data_path_remote: /nobackup/users/allisone/UROP_2025_Summer/Perceiver-diffusion-autoencoder/data/
  models_path_remote: /nobackup/users/allisone/UROP_2025_Summer/Perceiver-diffusion-autoencoder/models/

model_type: null
test_name: tessv1      # Name of test, to organize models and results
data_types: [lightcurves]    # Types of datasets (i.e. spectra, lightcurves)
data_names: [tessv1]   # Names of datasets, corresponding to data_types
process_lightcurves: true
train_from_checkpoint: false
checkpoint_path: null

training:
  epochs: 350
  lr: 1e-4
  weight_decay: 1e-5
  batch: 16
  aug: null
  accelerator: 'cuda'

unimodal:
  architecture:
    classifier:
      classifier_type: mlp
      shape:
        num_classes: 8
        weight_by_class: false
      components:
        classifier_dropout: null
        regularize: null
    encoder:
      use_pretrained_encoder: true
      pretrained:
        pretrained_encoder_path: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/tess_20k/daep_reconstructor_unimodal_lightcurves/dim_16-16-64-4-4-4-128_uncertFalse_concatTrue_sinposFalse_fourierTrue_lr0.00025_weight_decay1e-5_date2025-08-21_22-15
        pretrained_epoch: -1
        freeze_pretrained_encoder: true
      new:
        shape:
          bottlenecklen: null
          bottleneckdim: null
          model_dim: null
          encoder_layers: null
          encoder_heads: null
        components:
          concat: null
          cross_attn_only: null
          regularize: null
          sinpos_embed: null
          fourier_embed: null

multimodal:
  architecture:
    classifier:
      shape:
        num_classes: null
        classifier_dropout: null
        regularize: null
    encoder:
      use_pretrained_encoder: true
      pretrained:
        pretrained_encoder_path: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/lightcurves/tess_20k/TESSlightcurve_16-16-4-4-4-4-256_useUncertaintyFalse_sinposTrue_fourierTrue_concatTrue_crossattnonlyFalse_lr0.00025_batch16_reg0.0_aug1_date2025-08-07_10-12/ckpt/epoch_150_date_2025-08-07_14-44.pth
        freeze_pretrained_encoder: true
      new:
        shape:
          bottlenecklen: null
          bottleneckdim: null
          model_dim: null
          encoder_layers: null
          decoder_layers: null
          encoder_heads: null
          decoder_heads: null
          spectra_tokens: null
          photometry_tokens: null
        components:
          dropping_prob: null
          concat: null
          cross_attn_only: null
          mixer_selfattn: null
          regularize: null
          sinpos_embed: null
          fourier_embed: null
          use_uncertainty: null

testing:
  checkpoint_dir_path: null
  num_lightcurves: null
  num_samples: null
  num_examples: null
  save_results: null
  batch: null