env: local

data:
  data_path_local: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/data/
  models_path_local: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/
  data_path_remote: /nobackup/users/allisone/UROP_2025_Summer/Perceiver-diffusion-autoencoder/data/
  models_path_remote: /nobackup/users/allisone/UROP_2025_Summer/Perceiver-diffusion-autoencoder/models/

model_type: null
test_name: tessgalah_1k      # Name of test, to organize models and results
data_types: [lightcurves, spectra]    # Types of datasets (i.e. spectra, lightcurves)
data_names: [tess_1k, galah_1k]   # Names of datasets, corresponding to data_types
train_from_checkpoint: false
checkpoint_path: null

training:
  epochs: 100
  lr: null
  weight_decay: null
  batch: 4
  aug: null
  accelerator: null

unimodal:
  architecture:
    shape:
      bottlenecklen: null
      bottleneckdim: null
      model_dim: null
      encoder_layers: null
      decoder_layers: null
      encoder_heads: null
      decoder_heads: null
    components:
      concat: null
      cross_attn_only: null
      regularize: null
      sinpos_embed: null
      fourier_embed: null
      use_uncertainty: null

multimodal:
  architecture:
    shape:
      bottlenecklen: null
      bottleneckdim: null
      model_dim: null
      encoder_layers: null
      decoder_layers: null
      encoder_heads: null
      decoder_heads: null
      spectra_tokens: null
      photometry_tokens: null
    components:
      dropping_prob: null
      concat: null
      cross_attn_only: null
      mixer_selfattn: null
      regularize: null
      sinpos_embed: null
      fourier_embed: null
      use_uncertainty: null

testing:
  checkpoint_dir_path: null
  num_test_instances: null
  num_samples: null
  num_examples: null
  save_results: null
  batch: null 