env: local

data:
  data_path_local: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/data/
  models_path_local: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/
  data_path_remote: /nobackup/users/allisone/UROP_2025_Summer/Perceiver-diffusion-autoencoder/data/
  models_path_remote: /nobackup/users/allisone/UROP_2025_Summer/Perceiver-diffusion-autoencoder/models/

training:
  epochs: 50
  lr: 2.5e-4
  weight_decay: 1e-5
  batch: 4
  save_every: 5
  aug: null
  accelerator: 'cuda'

unimodal:
  architecture:
    classifier:
      shape:
        num_classes: null
      components:
        classifier_dropout: null
        regularize: null
    encoder:
      use_pretrained_encoder: true
      pretrained:
        pretrained_encoder_path: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/tess_20k/daep_reconstructor_unimodal_lightcurves/dim_16-16-4-4-4-4-256_uncertFalse_concatTrue_sinposTrue_fourierFalse_lr0.00025_weight_decay1e-5_date2025-08-11_12-22/
        pretrained_epoch: -1
        freeze_pretrained_encoder: true
      new:
        shape:
          bottlenecklen: null
          bottleneckdim: null
          model_dim: null
          encoder_layers: null
          encoder_heads: null
        components:
          concat: null
          cross_attn_only: null
          regularize: null
          sinpos_embed: null
          fourier_embed: null

multimodal:
  architecture:
    classifier:
      shape:
        num_classes: null
        classifier_dropout: null
        regularize: null
    encoder:
      use_pretrained_encoder: true
      pretrained:
        pretrained_encoder_path: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/lightcurves/tess_20k/TESSlightcurve_16-16-4-4-4-4-256_useUncertaintyFalse_sinposTrue_fourierTrue_concatTrue_crossattnonlyFalse_lr0.00025_batch16_reg0.0_aug1_date2025-08-07_10-12/ckpt/epoch_150_date_2025-08-07_14-44.pth
        freeze_pretrained_encoder: true
      new:
        shape:
          bottlenecklen: null
          bottleneckdim: null
          model_dim: null
          encoder_layers: null
          decoder_layers: null
          encoder_heads: null
          decoder_heads: null
          spectra_tokens: null
          photometry_tokens: null
        components:
          dropping_prob: null
          concat: null
          cross_attn_only: null
          mixer_selfattn: null
          regularize: null
          sinpos_embed: null
          fourier_embed: null

testing:
  checkpoint_dir_path: null
  num_lightcurves: null
  num_samples: null
  num_examples: null
  save_results: null
  batch: null