env: local

testing:  
  # Override with model directory (containing ./checkpoints and ./hparams.yaml)
  model_dir: /home/altair/Documents/UROP/2025_Summer/Perceiver-diffusion-autoencoder/models/tessgalah_20k/daep_reconstructor_multimodal_spectra_lightcurves/dim_16-16-4-4-4-4-256-256-256_modaldropP0.2_concatTrue_sinposTrue_fourierFalse_mixerselfattnTrue_lr0.00025_weight_decay1e-5_date2025-08-12_00-59
  num_test_instances: 3
  num_samples: null
  num_examples: 3
  save_results: null
  batch: 4